export const ON_MOUSE_HANDLER_MOVIE = 'ON_MOUSE_HANDLER_MOVIE';
export const OFF_MOUSE_HANDLER_MOVIE = 'OFF_MOUSE_HANDLER_MOVIE';
export const SHOW_MOVIE_START = 'SHOW_MOVIE_START';
export const SHOW_MOVIE_SUCCESS = 'SHOW_MOVIE_SUCCESS';
export const SHOW_MOVIE_FAIL = 'SHOW_MOVIE_FAIL';


export const FETCH_CHART_START = 'FETCH_CHART_START';
export const FETCH_CHART_SUCCESS = 'FETCH_CHART_SUCCESS';
export const FETCH_CHART_FAIL = 'FETCH_CHART_FAIL';


export const SHOW_MOVIE_COMMENTS_START = 'SHOW_MOVIE_COMMENTS_START';
export const SHOW_MOVIE_COMMENTS_SUCCESS = 'SHOW_MOVIE_COMMENTS_SUCCESS';
export const SHOW_MOVIE_COMMENTS_FAIL = 'SHOW_MOVIE_COMMENTS_FAIL';
export const SEND_NEW_COMMENT_SUCCESS = 'SEND_NEW_COMMENT_SUCCESS';